### PR TITLE
Adding allegro hands (left and right)

### PR DESCRIPTION
**Pull request by lmontaut**
Python api: `example-robot-data.load("allegro_right_hand" or "allegro_left_hand")` .

### CODE REVIEW

**Comment by hrp2-14** [comment]
Hi ! This project doesn't usually accept pull requests on the main branch.
If this wasn't intentionnal, you can change the base branch of this PR to devel
(No need to close it for that). Best, a bot.

**Review by nim65s — APPROVED** [review]
Thanks

**Comment by lmontaut** [comment]
Btw the allegro hand looks like:
image

**Review by cmastalli — APPROVED** [review]
Thanks!

**Review by jcarpent — APPROVED** [review]

**Pull request merged**
