### PR TITLE
Fix package paths in URDFs - resolve issues 9,19

### LINKED ISSUE #9: Using meshes provided by example-robot-data
Following recent discussions, I propose to move forward in  the direction of using meshes provided by example-robot-data instead of native description packages.

I will propose a pull request handling robots for which I will have tested that this does not break anything when loading models.

I also propose to revert commit ed85b87 since @cmastalli uses the lighting provided by the models.

### LINKED ISSUE #19: Redefine the mesh path for all robots to match URDF convention
This task was partially done for the UR robot. We need to
 1. Modify all URDF files to match convention
 2. Add README documentation (optional)

### PR DESCRIPTION
**Pull request by wxmerkt**
This PR resolves #19 with the exception of Solo, which I assume Guilhem will add to #20 (not added here to avoid conflicts).

Resolves #9 
Resolves #19

### CODE REVIEW

**Comment by nim65s** [comment]
Thanks for this @wxmerkt !

**Comment by nim65s** [comment]
I double checked it, and it works well both in CI and in my local setup, with a `ROS PACKAGE_PATH` only pointing to the install prefix. Maybe another step would be to add a visual test setting the `ROS_PACKAGE_PATH` to the source dir, to check that we can see the robots before installing the package, but that's another story.

**Comment by cmastalli** [comment]
@nim65s do you think we should describe the need to set up `ROS_PACKAGE_PATH` variable in the README file?

**Comment by nim65s** [comment]
That's a good idea.

**Comment by wxmerkt** [comment]
In a catkin workspace that is what happens when you have a devel or an install workspace automatically. 

If added to the README, then it needs to be explicit that it **only** applies to the vanilla-CMake installation method, otherwise we could see people starting to mess with their ROS_PACKAGE_PATH and end up with hard to debug errors.

**Comment by nim65s** [comment]
Also, on Arch, with https://aur.archlinux.org/packages/example-robot-data, I'm installing it in `/usr`, so it also works with an empty `ROS_PACKAGE_PATH`.

**Pull request merged**
