### PR TITLE
add talos full

### PR DESCRIPTION
**Pull request by nim65s**
To avoid a dependency to https://github.com/stack-of-tasks/talos-data/ in many packages.

### CODE REVIEW

**Review by cmastalli — COMMENTED** [review]
Hi @nim65s 

What is the reason to add new mesh files? It seems the `.STL` are copies of the `.stl`.
On the other words, could we use the `.stl` inside `talos_full_v2.urdf`?

Carlos

**Comment by nim65s** [comment]
Thanks @cmastalli, that's right, I fixed that.

**Comment by cmastalli** [comment]
Checking again, I see a mixture of `.stl` and `.STL`, maybe it makes sense to clean up the repo. For instance, we could make all of them `.stl` and modify the urdf respectively.

**Comment by nim65s** [comment]
Yes, this is sad, but I don't see any reason to do this. Everything already works fine this way, and each modification we made at this point will have to be taken in account if we ever want to update anything from the upstream repo.

**Review by cmastalli — APPROVED** [review]
I understand the motivation of keeping `stl` and `STL`.
Maybe we should solve this first in the root repo, but we depends upon the agreement with other partners.

Having a single format will avoid duplication.

**Pull request merged**
