### PR TITLE
[solo] disable collision pairs for adjacent links

### PR DESCRIPTION
**Pull request by pFernbach**
Without this changes, the robot is always in self-collision according to hpp-fcl. 

Should I also push this in https://github.com/open-dynamic-robot-initiative/robot_properties_solo ? This repo doesn't have any srdf file.

### CODE REVIEW

**Comment by jmirabel** [comment]
Yes, I think it would be good to have the SRDF file in the repo you mentioned. This repo is not supposed to be the main repo for any robot.

**Comment by cmastalli** [comment]
> Should I also push this in https://github.com/open-dynamic-robot-initiative/robot_properties_solo ? This repo doesn't have any srdf file.

I think this should be answered by the main developers / responsables of that repo.

**Comment by cmastalli** [comment]
If there is no anymore to be done, then let's merge it :)

**Comment by pFernbach** [comment]
PR done in the main repository for solo: https://github.com/open-dynamic-robot-initiative/robot_properties_solo/pull/22

**Comment by nim65s** [comment]
Hum, I shouldn't have merged this yet, as we have some inputs on the other PR. We might have to do another PR later, sorry.

**Pull request merged**
