### PR TITLE
Add laikago description

### PR DESCRIPTION
**Pull request by proyan**
The current PR adds the laikago description from https://github.com/unitreerobotics/laikago_ros, and updates it with meshes provided by @Kongx231. The urdf file is updated to rename the robot "laikago" instead of "laikago_description"

### CODE REVIEW

**Comment by nim65s** [comment]
Hi,

I think we don't need the files with extensions rviz, launch, backup and xacro in this package.
Also, we should choose between either dae or obj + mtl. As the urdf references the obj, I think we should also remove the dae.

Also, this is missing unit tests ;)

**Comment by cmastalli** [comment]
Hey guys, what is the status of this PR?

**Comment by nim65s** [comment]
@proyan : do you want me to clean this ?

**Comment by proyan** [comment]
I had completely forgotten about this PR.
I can push the required changes today, sorry about the wait

**Comment by proyan** [comment]
I've rebased and pushed the fixes.

**Review by nim65s — APPROVED** [review]
perfect, thanks !

**Review by cmastalli — APPROVED** [review]

**Comment by cmastalli** [comment]
Thanks @proyan !!!

**Pull request merged**
