### PR TITLE
Add go2 description

### PR DESCRIPTION
**Pull request by edantec**

### CODE REVIEW

**Review by nim65s — CHANGES_REQUESTED** [review]
This is adding 50M to the repo, which is already way too big.

No other robot folder is that big. 
PR2 is 1.7M, talos 7.4M for comparison.

Can you try to reduce the meshes ? Surely we don't need that level of detail for examples and unit tests

**Comment by edantec** [comment]
Meshes now weight 5.5 Mo, is it light enough? I used Blender to decimate the geometries.

**Comment by nim65s** [comment]
Way better, thanks a lot :D
Can you just double check they appear correctly on our viewers: meshcat / gepetto-gui / rviz / panda.
Maybe not all of those, but at least the 2 your prefer

After that, you also need to add an unit test, and this is good for me (we must squash the commits, though, otherwise we'll still have those 50M added in the repo)

**Review by cmastalli — COMMENTED** [review]
I have two comments somehow related:
  1. Can we reuse the mesh files from Go1? Are they fundamentally different?
  2. Can we reuse the SRDF file from Go1?

It seems that point 2 is quite doable. Name of links and bodies look similar.

**Comment by edantec** [comment]
Capture d’écran du 2024-10-10 14-41-44
Capture d’écran du 2024-10-10 14-41-28

Here is what the go2 looks like with simplified meshes. What do you think? It seems good enough to me.

**Comment by edantec** [comment]
> I have two comments somehow related:
> 
>     1. Can we reuse the mesh files from Go1? Are they fundamentally different?
> 
>     2. Can we reuse the SRDF file from Go1?
> 
> 
> It seems that point 2 is quite doable. Name of links and bodies look similar.

I actually reused the srdf file from go1 to create the one for go2. Standing position is different though, I modified the SRDF accordingly.
As for the mesh files, they are quite different.

**Comment by nim65s** [comment]
Yes, I think this is good enough, thanks !
Can you just add a unit test for the loader with the right nq / nv ?

**Comment by edantec** [comment]
> Yes, I think this is good enough, thanks ! Can you just add a unit test for the loader with the right nq / nv ?

Done. I noticed however that the test is not passing for the pr2 robot.

**Comment by nim65s** [comment]
pr2 test seems ok on CI tho

**Pull request merged**
