### PR TITLE
Remove lights from Anymal robot

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by nim65s** [comment]
I don't really get the rationale, but #8 removed the lights from ur and was accepted, so I guess we should also accept this here.

**Review by nim65s — APPROVED** [review]

**Comment by jcarpent** [comment]
The idea is to remove lights that are not welcome when one's perform rendering of the scene
There is no reason to have lights in DAE files, except the ones coming from the internal illumination of the scene.

**Comment by cmastalli** [comment]
How does the visualization change in GVr?
Could you share a pic?

If I remember correctly, it was badly displayed in GV without the lights.

**Comment by jmirabel** [comment]
For reference, there is a `gui.removeLightSources` in GV that remove all lights from a node.

**Comment by jcarpent** [comment]
> How does the visualization change in GV?
> Could you share a pic?
> 
> If I remember correctly, it was badly displayed in GV without the lights.

If you want a better illumination in GV, you need to add an omnidirectional light on top of the scene. But the lights should not be embedded inside the meshes. Otherwise, when the robot moves, the lighting changes too.

**Comment by jcarpent** [comment]
> For reference, there is a `gui.removeLightSources` in GV that removes all lights from a node.

Thanks for the hint.

**Pull request merged**
