### PR TITLE
Adds the Bolt robot to the repo

### LINKED ISSUE #71: Add bolt robot
eg. from https://github.com/open-dynamic-robot-initiative/robot_properties_bolt/tree/master/src/robot_properties_bolt/robot_properties_bolt

thanks @gfadini for raising the issue :)

### PR DESCRIPTION
**Pull request by jviereck**
Fixes #71 .

### CODE REVIEW

**Review by nim65s — CHANGES_REQUESTED** [review]
The URDF mention only STL meshes, so could you amend your commit to remove the obj ? This repository is already quite huge ^^"

**Comment by jviereck** [comment]
Good catch! Will do the cleanup later today.

**Comment by cmastalli** [comment]
Thanks for this contribution ;)

It would be also nice if you remove those files from the git history.

**Comment by jviereck** [comment]
I've removed the `obj` files and squashed the commits to remove them from the git history.

**Review by nim65s — APPROVED** [review]
Perfect, thanks !

**Comment by jviereck** [comment]
The gitlab-ci  is failing. How can I see why?

**Comment by cmastalli** [comment]
> The gitlab-ci is failing. How can I see why?

If you clip in "Details" you can see where it is failing. You should also run locally the unittests.
Btw, you also need to resolve some conflicts with the devel branch.

**Comment by jviereck** [comment]
Thanks @cmastalli for the hint about pressing "Details".

It also seems as if the unittests are failing. I take a look.

**Comment by jviereck** [comment]
All checks pass and the commits are rebased for devel.

Please let me know if there is anything else to do before this can be merged.

**Pull request merged**
