### PR TITLE
python: allow loading of multiple robots

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

The first commit is because I saw in our code base that people are using helpers to load our robots, but then need urdf / srdf paths for something else, and have to recompute that by themselves.

The second commit was a request from @thomasfla

### CODE REVIEW

**Review by cmastalli — COMMENTED** [review]
I would suggest to have a single function for retrieving the paths, rather than appending them inside `robot`.

Indeed, it would be better to do the same for `q0`.

**Comment by nim65s** [comment]
If we try to do this with a simple user-facing API, I think we only end up with a RobotWrapperWrapper, which proxy RobotWrapper plus add `q0` and 3 paths. Is this what we want ?

**Comment by nim65s** [comment]
Another option would be to expose those things directly in pinocchio's RobotWrapper. For me, the main issue is that `q0` collides with something already defined differently in pinocchio: 

https://github.com/stack-of-tasks/pinocchio/blob/17c479e2fe91905122713643f489feb8ddf135a3/bindings/python/pinocchio/robot_wrapper.py#L33

**Comment by proyan** [comment]
Could we merge this? Who has write access on this repo?

**Review by proyan — APPROVED** [review]

**Comment by cmastalli** [comment]
> Could we merge this? Who has write access on this repo?

The current solution appends the path into the robotwrapper class.
It would be ideal to do not do it, it also requires the user to learn that we pass a modified version of the robotwrapper.

What I propose is to create a dedicated function to retrieve the paths, and eventually another one to get the default state.

**Comment by nim65s** [comment]
@cmastalli : We can't have a "simple" function, can we ? Could you outline the prototype of the function you are thinking about ?

**Comment by cmastalli** [comment]
> @cmastalli : We can't have a "simple" function, can we ? Could you outline the prototype of the function you are thinking about ?

What about
 - `getUrdfPath('robot')`
 - `getSrdfPath('robot')`
 - `getDefaultConfiguration(`robot`)`
?

(or something like that)

**Pull request merged**
