### PR TITLE
Fix issue in ur robot #17

### PR DESCRIPTION
**Pull request by cmastalli**
This PR reverts commit 2545adcf0bbecd43ed40d6be03820cb53f3a16d7.

### CODE REVIEW

**Comment by nim65s** [comment]
We already had tons of discussions in #8 so let's wait for others to comment here.

**Comment by wxmerkt** [comment]
No, this is incorrect and will break things when resolving these URDFs via rospy or rospack, or in RViz. 

Background: We do not provide `ur_description`. The package is called `example-robot-data`, and as thus needs to be resolved with respect to the origin of this package. As thus, the fix in #8 was correct. If this causes an issue with Pinocchio or other path resolvers, we should look into fixing it there. Accepting this PR would break the URDFs or require additional packages to be installed (`ur_description` in this case) - making the point of this package kind of moot.

**Comment by cmastalli** [comment]
> No, this is incorrect and will break things when resolving these URDFs via rospy or rospack, or in RViz.
> 
> Background: We do not provide `ur_description`. The package is called `example-robot-data`, and as thus needs to be resolved with respect to the origin of this package. As thus, the fix in #8 was correct. If this causes an issue with Pinocchio or other path resolvers, we should look into fixing it there. Accepting this PR would break the URDFs or require additional packages to be installed (`ur_description` in this case) - making the point of this package kind of moot.

If we reject this PR, then we need to adopt the new policy for all repositories. At the time being, UR description is different to the other cases.

It would be great to modify the loader script in such a way that we don't need to define `ROS_PACKAGE_PATH`. This package should not depend on `ROS`, as any software in the planet.

**Comment by wxmerkt** [comment]
Per the URDF convention, the path should be respective to the root of the package it is referring in `package://`. As the `robots/ROBOTNAME` folders are not the source of a separate package (e.g. there would have to be a `package.xml` specifying the name as `ur_description`), the root is the repository root. And as thus the UR URDF is correct.

Which loader gets tripped up by this and would requite the additional variable set?

**Comment by cmastalli** [comment]
I will close this PR as the proposed solution seems to be not the standard one.

I have created an issue for this topic #19.

**Pull request closed without merging**
