### PR TITLE
Add Panda robot

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
After the merge, I will make a new release for Conda.

**Comment by nim65s** [comment]
Please don't merge yet, this is not working for me, with 
`ValueError: Mesh package://example-robot-data/robots/panda_description/meshes/collision/link0.stl could not be found.`

**Comment by jcarpent** [comment]
> Please don't merge yet, this is not working for me, with
> `ValueError: Mesh package://example-robot-data/robots/panda_description/meshes/collision/link0.stl could not be found.`

This is related to the issue #35 that I've just opened. It is the case for all the robots @nim65s.

**Comment by nim65s** [comment]
My issue here was related to #24 ; after installation, I have another issue:
```
ValueError: Mesh index: 0
Face index: 0
```

**Comment by nim65s** [comment]
I followed https://github.com/stack-of-tasks/pinocchio/issues/838 and opened the meshes with freecad, exported them as dae again, and the unit tests are passing now.

**Pull request merged**
